# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Jogja EduFair 2017"
email: "jogjaedufair@gmail.com"
description: "Jogja EduFair merupakan sebuah event tahunan yang diselenggarakan oleh Prodi Teknologi Pendidikan Universitas Negeri Yogyakarta"
baseurl: ""
url: "https://sigit.purwadi.web.id"
permalink: "/blog/:title"
# googleAnalyticsTrackingId: "UA-43643469-5"
# googleAnalyticsSiteUrl: "gdg-x.github.io"
# siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "Educational Technology"
organizerAlternateName: "Educational Technology Yogyakarta State University"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "jogjaedufair@gmail.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "/"

# Head
metaKeywords: "event, edtech, yogyakarta, education, universitas negeri yogyakarta, teknologi pendidikan"
twitterAccount: "@JogjaEduFair"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/direction/", text: "Direction"}
 - {permalink: "/footprint/", text: "Footprint"}
# - {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 - {link: "https://bit.ly/dfua-c4p", text: "Become a sponsor"}
rightNavigationButtons:
 - {link: "https://bit.ly/dfua-c4p", text: "Become a sponsor"}

# Hero Block
heroImage: "hero2.jpg"
heroTitle: "Jogja EduFair <typeout> 2017"
eventDate: "on May"
typeoutTextValues: '"", "Exhibitions", "EdTech", "Talkshow", "Workshops", "Playground", "Training", "Have fun"'
typeoutFallback: "Exhibitions"
heroButtons:
 - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
 - {permalink: "/#partners", text: "Become a sponsor"}
 ##- {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "About Jogja EduFair 2017"
aboutBlock:
 - {title: "Exhibition", image: "exhibition.jpg", text: "The biggest Google related event in the country carefully crafted for you by GDG community! Awesome speakers and lots of fun!" }
 - {title: "Seminar", image: "seminar.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }
 - {title: "Talkshow", image: "seminar.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }
 - {title: "Playground", image: "playground.jpg", text: "Full-day freestyle hackathon! Want some real team building on friday? Grab your team and join our hackathon!" }
 - {title: "Edu Clinic", image: "workshop.jpg", text: "The biggest Google related event in the country carefully crafted for you by GDG community! Awesome speakers and lots of fun!" }


# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "2000", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "120", specialCharacter: "+", info: "media", detail: "exhibitions"}
 - {count: "10", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
 - {count: "5", specialCharacter: "", info: "artists", detail: "and local communities"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Grhatama Pustaka"
eventLocationLink: "https://www.facebook.com/grhatamapustaka/"
eventStreetAddress: "Jalan Janti, Banguntapan"
eventAddressLocality: "Bantul"
eventAddressLocalityRegion: "Yogyakarta"
eventPostalCode: "55198"
eventAddressCountry: "Indonesia"
eventStartTime: "2017-03-01T10:00"
eventDoorTime: "09:00"
eventEndTime: "2017-03-30T20:00"
eventPlaceCoordinates: "-7.7985579,110.4058781"
mapCenterCoordinates: "-7.7992579,110.4028281"
mapMobileCenterCoordinates: "-7.8001749,110.4065381"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Grhatama Pustaka"
venueFeatures: ["Indonesian biggest library", "with 6D Cinema", "Located directly in the city center"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "JogjaEduFair"
twitterFeed: "https://twitrss.me/twitter_user_to_rss/?user=jogjaedufair"
# twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Open Sponsor"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Gold Sponsor"
  price: "1000 - 4900"
  priceCurrency: "k"
  ticketsNumber: "150"
  ribbon: ""
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Logo on website", "Meet our sponsor blog post", "Banners on the stage"]
  validFrom: "2017-02-01T10:00"
  validThrough: "2017-04-20T23:59"
 -
  name: "Diamond Sponsor"
  price: "5000 - 10000"
  priceCurrency: "k"
  ticketsNumber: "100"
  ribbon: ""
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Logo on website", "Booth Space", "Banners on the stage"]
  validFrom: "2017-02-01T00:00"
  validThrough: "2017-04-20T23:59"
  disabled: false
 -
  name: "Silver Sponsor"
  price: "500 - 900"
  priceCurrency: "k"
  ticketsNumber: "50"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Logo on website", "Goodiebag inserts", "Banners in the conference hall"]
  validFrom: "2017-02-01T10:00"
  validThrough: "2017-04-20T23:59"
  soldOut: true
  soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://instagram.com/jogjaedufair", icon: "instagram"}
 - {link: "https://twitter.com/intent/user?screen_name=JogjaEduFair", icon: "twitter"}
 - {link: "https://facebook.com/GDGLviv", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://uny.ac.id", text: "Universitas Negeri Yogyakarta"}
   - {link: "http://diesnatalis.uny.ac.id", text: "Dies Natalis UNY"}
   - {link: "https://http://kurikulum-teknologi-pendidikan.fip.uny.ac.id/", text: "Kurikulum dan Teknologi Pendidikan"}
 -
  title: "Contacts"
  links:
   - {link: "https://www.google.com/maps?z=16&q=laboratorium+jurusan+kurikulum+dan+teknologi+pendidikan,+gedung+pusat+fip+lantai+2,+uny,+jalan+colombo+no+1+ct,+depok,+sleman", text: "Laboratorium Jurusan Kurikulum dan Teknologi Pendidikan, Gedung pusat FIP lantai 2, UNY, Jalan Colombo no 1 CT, Depok, Sleman  
"}
   - {link: "tel:+6289656571751", text: "+62896-5657-1751 (Tera)"}
   - {link: "mailto:jogjaedufair@gmail.com", text: "jogjaedufair@gmail.com"}
 -
  title: "Download"
  links:
   # - {permalink: "/cod/", text: "Code of Conduct"}
   - {permalink: "/", text: "Pamflet"}
   - {permalink: "/assets/denah.jpg", text: "Denah Lokasi"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "jogja-edufair-2017"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "-7.7992579, 110.4028281"
logisticsMapMobileCenterCoordinates: "-7.8001749, 110.4065381"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
# directionDetailsImage: "direction-details.jpg"
directionDetailsImage: "hero2.jpg"
directionDetailsTitle: "Get around Jogja"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: false

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"

# Hackathon About Block
aboutFootprintTitle: "EdTech in action"
aboutFootprint: "Pameran Teknologi Pendidikan merupakan sebuah event tahunan yang diselenggarakan oleh Prodi Teknologi Pendidikan Universitas Negeri Yogyakarta. Bertujuan untuk memperkenalkan hasil kreasi dan inovasi dalam bidang pendidikan yang menjadi wilayah garapan Prodi Teknologi Pendidikan seperti multimedia pembelajaran, audio video pembelajaran, alat permainan edukatif, modul-modul pembelajaran, hingga metode – metode pembelajaran. Kreasi dan inovasi ini diciptakan dan dikembangkan mengikuti perkembangan teknologi yang ada."
footprintRows:
 - {title: "2013", image: "hackathon-0.png", details: "Diselenggarakan di Benteng Vredeburg dengan menghadirkan bintang tamu jazz terkenal Paksi Raras Alit dan juga mengadakan berbagai lomba untuk pelajar dan masyarakat umum. Event ini dihadiri oleh ratusan pengunjung yang terdiri dari mahasiswa, praktisi pendidikan, pelajar, maupun masyarakat."}
 - {title: "2014", image: "hackathon-1.png", details: "Diselenggarakan di Museum Pendidikan Indonesia dengan tajuk acara adalah Festival Teknologi Pendidikan “Yo Dolan Yo Sinau”. Kegiatan yang diselenggarakan, adalah pameran media pembelajaran, seminar nasional, lomba mewarnai, lomba fotografi untuk pembelajaran, lomba kreativitas siswa dan pagelaran seni dan budaya. Event ini dihadiri oleh 1040 pengunjung yang terdiri dari mahasiswa, praktisi pendidikan, pelajar, maupun masyarakat."}
 - {title: "2015", image: "hackathon-2.png", details: "Memiliki 4 jenis kegiatan pameran yaitu Jogjacation yang bertempat di Benteng Vresdeburg, Pameran Teknologi Pendidikan yang bertempat di Museum Pendidikan Indonesia, Roadshow ke beberapa sekolah di DIY, dan Pameran di SMK Negeri 2 Kasihan Bantul. Event ini dihadiri oleh ratusan pengunjung yang terdiri dari mahasiswa, praktisi pendidikan, pelajar, maupun masyarakat umum."}
 - {title: "2016", image: "hackathon-2.png", details: "Dengan mengambil semangat Semarak Pendidikan Yogyakarta, pameran ini bertemakan My Life My Education merupakan sebuah tema yang mengusung ide besar tentang cara pandang manusia dimana ia memaknai setiap jengkal perjalanan hidupnya sebagai sebuah proses pendidikan tiada akhir. Dengan rangkaian acara workshop, talkshow, dan lomba yang ditujukan untuk semua kalangan. Event ini dihadiri sekitar 2000 pengunjung dari berbagai kalangan."}
